 import 'package:flutter/material.dart';
import 'package:smacredit/src/payments/models/transaction.dart';

final List<Transaction> mockTransactions = [
    Transaction(
      logoUrl: 'assets/starbucks.png',
      logoColor: Colors.green,
      companyName: 'Rebecca_craft',
      type: 'Transfer',
      date: 'Friday 22 March',
      time: '14:14:14',
      amount: 23.50,
    ),
    Transaction(
      logoUrl: 'assets/samsung.png',
      logoColor: Colors.blue,
      companyName: 'David_lyle',
      type: 'Payment',
      date: 'Saturday 16 March',
      time: '11:15:00',
      amount: 150.00,
    ),
    Transaction(
      logoUrl: 'assets/huawei.png',
      logoColor: Colors.red,
      companyName: 'Sam_jones',
      type: 'Transfer',
      date: 'Wednesday 13 March',
      time: '09:45:00',
      amount: 25.00,
    ),
    Transaction(
      logoUrl: 'assets/acme.png',
      logoColor: Colors.grey,
      companyName: 'Acme_software',
      type: 'Bank Transfer',
      date: 'Wednesday 20 March',
      time: '12:00:00',
      amount: 100.00,
    ),
    Transaction(
      logoUrl: 'assets/samsung.png',
      logoColor: Colors.blue,
      companyName: 'Olivia_hart',
      type: 'Bank Transfer',
      date: 'Friday 15 March',
      time: '16:30:00',
      amount: 75.00,
    ),
    Transaction(
      logoUrl: 'assets/huawei.png',
      logoColor: Colors.red,
      companyName: 'Book Store',
      type: 'Bank Transfer',
      date: 'Tuesday 12 March',
      time: '15:30:00',
      amount: 30.00,
    ),
    Transaction(
      logoUrl: 'assets/starbucks.png',
      logoColor: Colors.green,
      companyName: 'Coffee Shop',
      type: 'Payment Request',
      date: 'Tuesday 19 March',
      time: '08:30:00',
      amount: 5.50,
    ),
    Transaction(
      logoUrl: 'assets/samsung.png',
      logoColor: Colors.blue,
      companyName: 'Tech Gadgets',
      type: 'Donation',
      date: 'Thursday 14 March',
      time: '14:00:00',
      amount: 250.00,
    ),
    Transaction(
      logoUrl: 'assets/samsung.png',
      logoColor: Colors.blue,
      companyName: 'Tech Gadgets',
      type: 'Donation',
      date: 'Thursday 14 March',
      time: '14:00:00',
      amount: 250.00,
    ),
  ];
