org.gradle.jvmargs=-Xmx8G -XX:MaxMetaspaceSize=4G -XX:ReservedCodeCacheSize=512m -XX:+HeapDumpOnOutOfMemoryError
android.useAndroidX=true
android.enableJetifier=true
android.defaults.buildfeatures.buildconfig=true
ANDROID_NDK_VERSION=27.0.12077973
android.cmakeVersion=3.22.1
kotlin.jvm.target=17
kotlin.jvm.target.validation.mode = IGNORE

