-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQg9umoJOil6aKiIUth
iuPbEgvbiCtjg2weHYCHN78p3TqgCgYIKoZIzj0DAQehRANCAAQp5p8meF5eNjYc
HUSchvchnzPcbxgIogNaWWeGzimNKqGSn8ZPHSJOnxaF9li6gmPaglYsLcUqPJLy
07zgD3Tz
-----END PRIVATE KEY-----